require 'tty-spinner'
require 'colorize'

# Actual game function
# Randomizes questions and displays to user
# @params: [Array] Set of questions
def sample_question(question_set)
  total_questions = question_set.length() 
  wrong_answers = [] # a record of all the questions user got wrong
  order = 1  
  correct = 0 
  incorrect = 0 
  while order <= total_questions
    question = question_set.sample
    puts ''
    puts "Question #{order}/#{total_questions}: #{question["question"]}".cyan
    puts "Your answer is:".green
    answer = STDIN.gets.chomp.downcase
    # Allowing user to back out of game
    if answer.downcase == 'back'
      return false
      # Checking if answer matches answer in system and giving feedback
    elsif answer == question["answer"].downcase
      puts "Correct!".green
      correct += 1
    else 
      puts "Incorrect! The correct answer is:".red
      puts "#{question["answer"]}".green
      question['user_input'] = answer
      wrong_answers << question
      incorrect += 1
    end
    # Beginning next question and removing picked question from the pool
    order += 1
    question_set.delete(question)
  end 
  return {total_questions: total_questions, correct: correct, incorrect: incorrect, wrong_answers: wrong_answers}
end


# End of game results, totals how many user got correct vs total number of questions
# @params: [Hash] game report generated by sample_question
def report(result)
  correct_result = result[:correct]
  total_result = result[:total_questions]
  sum = correct_result/total_result.to_f * 100 # Maths to give a percentage
  puts ''
  puts "You got #{correct_result}/#{total_result} correct! That's #{sum}% of questions right!".cyan
  puts ''
  # Display incorrect answers
  puts "These are the questions you got wrong:".cyan
  result[:wrong_answers].each do |item|
    puts "- #{item['question']}"
    puts "You answered: #{item['user_input']}".cyan
    print "The answer was: '#{item['answer']}' ".green
    puts "You'll get it next time!".cyan
    puts ''
  end
  # Congratulation statements (basically a win/loss)
  if sum >= 70
    puts "Well done! You're pretty smart.".green 
  elsif sum < 70
    puts "Better luck next time.".red
  end
  puts ''
  puts "Thanks for playing!".cyan
end